name: web_admin_fitness
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  i18n_json: ^0.9.1
  auto_route: ^5.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  form_builder_validators: ^8.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  get_it: ^7.2.0
  flutter_form_builder: ^7.7.0
  ferry: ^0.14.0+1
  ferry_hive_store: ^0.5.1
  ferry_flutter: ^0.8.0+1
  gql_http_link: ^0.4.4+1
  gql_link: ^0.5.1-alpha+1667321107831
  gql_error_link: ^0.2.3
  gql_transform_link: ^0.2.3-alpha+1667321107848
  gql_exec: ^0.4.2-alpha+1667321107825
  event_bus: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  adaptive_dialog: ^1.8.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  cloudinary_flutter: ^0.0.4
  cloudinary_public: ^0.21.0
  image_picker: ^0.8.7+4
  video_player: ^2.6.1
  riverpod: ^2.3.2
  responsive_framework: ^0.2.0
  touchable_opacity: ^1.2.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.6
  share_plus: ^6.3.0
  syncfusion_flutter_datagrid: ^21.1.41
  adaptive_selector:
    git:
      url: https://github.com/lvxduck/adaptive_selector.git
      ref: feat/multiple_choice
  responsive_builder: ^0.6.4
  side_sheet: ^1.0.4
  url_strategy: ^0.2.0
  syncfusion_flutter_core: ^21.1.41
  sentry_flutter: ^6.18.1
  sentry_link: ^0.1.2
  flutter_svg: ^2.0.5
  built_value: ^8.4.4
  built_collection: ^5.1.1
  permission_handler: ^10.2.0
  device_info_plus: ^8.2.2
  app_settings: ^4.2.0
  path: ^1.8.2
  http: ^0.13.6
  path_provider: ^2.0.14
  flutter_slidable: ^3.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0
  ferry_generator: ^0.8.0+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/global/gen
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
